### ISSUE TITLE
Fix :watcher_command_error that disables FR-FG Risteys from running locally

### ISSUE THREAD

**Issue by SaraKuitunen** [dsgelab/risteys#212]
Running FR-FG Risteys locally by running `mix phx.server` doesn't work because of the below error

`[error] Task #PID<0.585.0> started from RisteysWeb.Endpoint terminating
** (stop) :watcher_command_error
    (phoenix 1.6.0) lib/phoenix/endpoint/watcher.ex:55: Phoenix.Endpoint.Watcher.watch/2
    (elixir 1.12.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib 3.15.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &Phoenix.Endpoint.Watcher.watch/2
    Args: ["node", ["node_modules/webpack/bin/webpack.js", "--mode", "development", "--watch-stdin", {:cd, "/Users/sarakuitunen/risteys/risteys_elixir/assets"}]]`

Running the failing JavaScript script `./node_modules/webpack/bin/webpack.js --mode development --watch-stdin` in `/assets` directory gives the following error:

`dyld[6630]: Library not loaded: '/usr/local/opt/icu4c/lib/libicui18n.69.dylib'
  Referenced from: '/usr/local/Cellar/node/16.6.2/bin/node'
  Reason: tried: '/usr/local/opt/icu4c/lib/libicui18n.69.dylib' (no such file), '/usr/local/lib/libicui18n.69.dylib' (no such file), '/usr/lib/libicui18n.69.dylib' (no such file), '/usr/local/Cellar/icu4c/71.1/lib/libicui18n.69.dylib' (no such file), '/usr/local/lib/libicui18n.69.dylib' (no such file), '/usr/lib/libicui18n.69.dylib' (no such file)
Abort trap: 6`

**Comment by SaraKuitunen** [comment]
Solved by `brew reinstall icu4c`
